# TODO: Clean up this.
# Most tools are here because Debian didn't have the latest version.
# Now, with Arch they can be removed from here and installed using Arch packages.

[tools]
aws-cli = "2.34.18"
aws-vault = "7.2.0"
ast-grep = "0.42.0"
"cargo:caligula" = "0.4.8"
"cargo:mergiraf" = "0.16.3"
"cargo:diskonaut" = "0.11.0"
delta = "0.19.1"
difftastic = { version = "0.68.0", exe = "difft" }
eza = "0.23.4"
fd = "10.4.2"
gh = "2.89.0"
go = "1.24.4"
node = "lts"
"npm:@mariozechner/pi-coding-agent" = "0.63.1"
"npm:@openai/codex" = "0.117.0"
"pipx:harlequin" = "2.5.2"
"pipx:ipython" = "9.12.0"
"pipx:llm" = "0.28"
"pipx:magic-beans" = "0.5.0"
"pipx:posting" = "2.9.2"
"pipx:ruff" = "0.15.8"
python = "3.13"
ripgrep = "15.1.0"
rust = "stable"
sd = "1.1.0"
starship = "1.24.2"
uv = "0.11.2"
zoxide = "0.9.9"

[settings]
idiomatic_version_file_enable_tools = ["node"]

[tasks]
bumpi = "mise up --bump -i"
