[tools]
aws-cli = { version = "2.34.38", symlink_bins = "true" }
ast-grep = "0.42.0"
"cargo:caligula" = "0.4.8"
"cargo:diskonaut" = "0.11.0"
"cargo:mergiraf" = "0.16.3"
delta = "0.19.1"
difftastic = { version = "0.68.0", exe = "difft" }
go = "1.24.4"
"go:github.com/grafana/gcx/cmd/gcx" = "0.2.12"
"go:github.com/jorgerojas26/lazysql" = "0.5.0"
node = "lts"
"npm:@earendil-works/pi-coding-agent" = "0.78.1"
"npm:@openai/codex" = "0.130.0"
"npm:napkin-ai" = "0.8.3"
"pipx:harlequin" = "2.5.2"
"pipx:ipython" = "9.12.0"
"pipx:jira-genie" = "0.4.0"
"pipx:magic-beans" = "0.7.0"
"pipx:posting" = "2.9.2"
"pipx:ruff" = "0.15.8"
pre-commit = "4.6.0"
python = "3.13"
rust = "stable"
sd = "1.1.0"
shellcheck = "0.11.0"
uv = "0.11.8"
terragrunt = "1.0.8"
terraform = "1.14"
heroku = "11.7.1"
"github:ogulcancelik/herdr" = "0.7.1"

[settings]
idiomatic_version_file_enable_tools = ["node"]
install_before = "7d"

[tasks]
bumpi = "mise up --bump -i"
