[tools]
ast-grep = "0.38.7"
"cargo:mergiraf" = "0.12.1"
delta = "0.18.2"
difftastic = "0.64.0"
eza = "0.22.1"
fd = "10.2.0"
gh = "2.75.0"
go = "1.24.4"
node = "22.16.0"
pandoc = "latest"
"pipx:llm" = "0.26"
"pipx:ruff" = "0.12.3"
python = "3.13.5"
ripgrep = "14.1.1"
ripgrep-all = "0.10.9"
rust = "stable"
starship = "1.23.0"
uv = "0.7.20"
zoxide = "0.9.8"

[settings]
idiomatic_version_file_enable_tools = ["node"]
