[tools]
ast-grep = "latest"
aws-vault = "latest"
"cargo:mergiraf" = "latest"
delta = "latest"
difftastic = "latest"
eza = "latest"
fd = "latest"
gh = "latest"
hugo-extended = "latest"
node = "22"
"npm:@anthropic-ai/claude-code" = "latest"
"npm:@openai/codex" = "latest"
"pipx:llm" = "latest"
poetry = "latest"
pre-commit = "latest"
python = "3"
ripgrep = "latest"
ripgrep-all = "latest"
rust = "stable"
starship = "latest"
uv = "latest"
zoxide = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node"]
