[tools]
ast-grep = "0.38.6"
"cargo:mergiraf" = "0.11.0"
delta = "0.18.2"
difftastic = "0.64.0"
eza = "0.22.0"
fd = "10.2.0"
gh = "2.74.2"
go = "1.24.4"
node = "22.16.0"
"pipx:llm" = "0.26"
"pipx:ruff" = "0.12.2"
python = "3.13.5"
ripgrep = "14.1.1"
ripgrep-all = "0.10.9"
rust = "stable"
starship = "1.23.0"
uv = "0.7.19"
zoxide = "0.9.8"

[settings]
idiomatic_version_file_enable_tools = ["node"]
